version: '3.9'
 
services:
  db:
    container_name: 'shopper_test_backend'
    image: postgres
    volumes:
      - storage_db:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: shopperDB
      
 
volumes:
  storage_db: {}